# Generated by Django 2.2.13 on 2021-01-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referentiel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('acronyme', models.CharField(max_length=80)),
                ('titre', models.CharField(max_length=255)),
                ('dblp', models.CharField(blank=True, max_length=255, null=True)),
                ('classement', models.CharField(max_length=10)),
                ('domaine', models.IntegerField()),
            ],
            options={
                'db_table': 'Referentiel',
            },
        ),
    ]
