# Generated by Django 3.1.7 on 2021-04-01 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=255)),
                ('id_hal', models.CharField(max_length=40, null=True, unique=True)),
            ],
            options={
                'db_table': 'Auteur',
            },
        ),
        migrations.CreateModel(
            name='ClassementPubli',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ClassementPubli',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom_hal', models.CharField(max_length=40, unique=True)),
                ('id_hal', models.IntegerField(null=True, unique=True)),
                ('nom', models.CharField(default='À définir', max_length=80)),
                ('description', models.TextField()),
                ('email_contact', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'Collection',
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('code', models.CharField(default='défaut', max_length=20, primary_key=True, serialize=False)),
                ('url_hal', models.CharField(default='https://api.archives-ouvertes.fr/search/', max_length=80)),
                ('annee_min_publis', models.IntegerField(default=2017)),
                ('annee_max_publis', models.IntegerField(default=2021)),
            ],
            options={
                'db_table': 'Config',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='')),
                ('description', models.CharField(max_length=255)),
                ('identifiant_source', models.CharField(max_length=30, unique=True)),
                ('delimiteur', models.CharField(default=';', max_length=5)),
                ('type_source', models.CharField(choices=[('CORE', "Fichier d'import CORE"), ('SCIMAGO', "Fichier d'import SCIMAGO"), ('INTERNE', "Fichier d'import format interne")], default='CORE', max_length=30)),
            ],
            options={
                'db_table': 'Source',
            },
        ),
        migrations.CreateModel(
            name='Referentiel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_locale', models.CharField(max_length=40, null=True)),
                ('type', models.CharField(default='COMM', max_length=10)),
                ('acronyme', models.CharField(max_length=80)),
                ('titre', models.TextField()),
                ('champ_plein_texte', models.TextField(default='')),
                ('classement', models.CharField(max_length=30)),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='publis.source')),
            ],
            options={
                'db_table': 'Referentiel',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('idHal', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('annee', models.IntegerField()),
                ('type', models.CharField(max_length=30)),
                ('chaine_auteurs', models.TextField(blank=True, null=True)),
                ('revue_titre', models.CharField(blank=True, max_length=255, null=True)),
                ('conf_titre', models.CharField(blank=True, max_length=255, null=True)),
                ('ouvrage_titre', models.CharField(blank=True, max_length=255, null=True)),
                ('classement_valide', models.BooleanField(default=False)),
                ('auteurs', models.ManyToManyField(blank=True, to='publis.Auteur')),
                ('classement', models.ForeignKey(default='I', on_delete=django.db.models.deletion.PROTECT, to='publis.classementpubli')),
                ('collections', models.ManyToManyField(blank=True, to='publis.Collection')),
            ],
            options={
                'db_table': 'Publi',
            },
        ),
    ]
