# Generated by Django 2.2.13 on 2021-01-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referentiel',
            name='acronyme',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
