# Generated by Django 3.1.7 on 2021-04-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='nom_hal',
            new_name='sigle_hal',
        ),
        migrations.AlterField(
            model_name='source',
            name='type_source',
            field=models.CharField(choices=[('CORE', 'Sources CORE'), ('SCIMAGO', 'Sources SCIMAGO'), ('INTERNE', 'Sources interne')], default='CORE', max_length=30),
        ),
    ]
