# Generated by Django 2.2.13 on 2021-01-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publis', '0002_auto_20210109_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referentiel',
            name='domaine',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
