# Generated by Django 3.1.7 on 2021-04-11 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publis', '0002_auto_20210406_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='idHal',
            new_name='id_hal',
        ),
    ]
