# Generated by Django 2.2.13 on 2021-01-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publis', '0003_auto_20210109_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referentiel',
            name='titre',
            field=models.TextField(),
        ),
    ]
