# Generated by Django 3.1.7 on 2021-04-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publis', '0003_auto_20210411_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='auteurs',
            field=models.ManyToManyField(related_name='collections', to='publis.Auteur'),
        ),
    ]
