# Generated by Django 2.2.13 on 2021-01-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publis', '0004_auto_20210109_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referentiel',
            name='classement',
            field=models.CharField(max_length=30),
        ),
    ]
