# Generated by Django 3.1.7 on 2021-04-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publis', '0004_auto_20210418_1644'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.UniqueConstraint(fields=('auteur', 'collection'), name='UnicitéAuteurCollection'),
        ),
    ]
