# Generated by Django 2.2.13 on 2021-01-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publis', '0005_auto_20210109_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='referentiel',
            name='champ_pleion_texte',
            field=models.TextField(default=''),
        ),
    ]
