# Generated by Django 3.1.7 on 2021-04-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publis', '0005_auto_20210418_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='conf_titre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='ouvrage_titre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='revue_titre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='titre',
            field=models.TextField(),
        ),
    ]
