# Generated by Django 2.2.13 on 2021-01-09 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publis', '0006_referentiel_champ_pleion_texte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referentiel',
            old_name='champ_pleion_texte',
            new_name='champ_plein_texte',
        ),
    ]
