# Generated by Django 3.1.7 on 2021-05-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publis', '0006_auto_20210418_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypesHAL',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'TypesHAL',
            },
        ),
    ]
