# Generated by Django 2.2.13 on 2021-01-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publis', '0007_auto_20210109_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='referentiel',
            name='type',
            field=models.CharField(default='COMM', max_length=10),
        ),
    ]
