# Generated by Django 3.1.7 on 2021-05-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publis', '0008_auto_20210513_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='types_publis',
            field=models.ManyToManyField(to='publis.TypesHAL'),
        ),
    ]
