# Generated by Django 3.2.11 on 2022-12-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publis', '0009_config_types_publis'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='repertoire_export',
            field=models.CharField(default='/tmp', max_length=100),
        ),
    ]
