# Generated by Django 3.2.11 on 2023-01-07 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publis', '0010_config_repertoire_export'),
    ]

    operations = [
        migrations.AddField(
            model_name='auteur',
            name='id_interne',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='auteur',
            name='nom',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='auteur',
            name='prenom',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
