# Generated by Django 2.2.13 on 2021-01-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_auto_20210110_0754'),
        ('publis', '0010_auto_20210109_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('idHal', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Auteur',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('idHal', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('annee', models.IntegerField()),
                ('type', models.CharField(max_length=30)),
                ('revue_titre', models.CharField(blank=True, max_length=255, null=True)),
                ('conf_titre', models.CharField(blank=True, max_length=255, null=True)),
                ('auteurs', models.ManyToManyField(blank=True, to='publis.Auteur')),
                ('equipes', models.ManyToManyField(blank=True, to='home.Equipe')),
            ],
            options={
                'db_table': 'Publi',
            },
        ),
    ]
