# Generated by Django 2.2.13 on 2021-01-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publis', '0011_auteur_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='ouvrage_titre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
