# Generated by Django 3.2.11 on 2023-01-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publis', '0011_auto_20230107_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auteur',
            name='id_interne',
            field=models.IntegerField(null=True),
        ),
    ]
