# Generated by Django 3.2.11 on 2023-01-08 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publis', '0012_alter_auteur_id_interne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auteur',
            name='id_hal',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
