# Generated by Django 2.2.13 on 2021-01-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publis', '0012_publication_ouvrage_titre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='auteurs',
        ),
        migrations.AddField(
            model_name='publication',
            name='auteurs',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
