# Generated by Django 2.2.13 on 2021-01-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publis', '0013_auto_20210110_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='auteurs',
            field=models.TextField(null=True),
        ),
    ]
