# Generated by Django 2.2.13 on 2021-01-11 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publis', '0014_auto_20210110_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referentiel',
            name='dblp',
        ),
        migrations.RemoveField(
            model_name='referentiel',
            name='domaine',
        ),
    ]
