# Generated by Django 2.2.13 on 2021-01-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publis', '0015_auto_20210111_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassementPubli',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ClassementPubli',
            },
        ),
    ]
