# Generated by Django 3.2.11 on 2023-02-23 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publis', '0016_auto_20230121_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuteurPos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=1)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publis.auteur')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publis.publication')),
            ],
        ),
    ]
