# Generated by Django 2.2.13 on 2021-01-13 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publis', '0017_auto_20210113_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='classement',
            field=models.ForeignKey(default='I', on_delete=django.db.models.deletion.PROTECT, to='publis.ClassementPubli'),
        ),
        migrations.AddField(
            model_name='publication',
            name='classement_valide',
            field=models.BooleanField(default=False),
        ),
    ]
