# Generated by Django 3.2.11 on 2023-02-23 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publis', '0017_auteurpos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='auteurs',
        ),
    ]
