# Generated by Django 3.2.11 on 2023-02-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publis', '0018_remove_publication_auteurs'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='auteurs',
            field=models.ManyToManyField(blank=True, through='publis.AuteurPos', to='publis.Auteur'),
        ),
    ]
