# Generated by Django 3.2.11 on 2023-03-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publis', '0019_publication_auteurs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeshal',
            name='code',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
