# Generated by Django 2.2.13 on 2021-01-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publis', '0020_source_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='delimiteur',
            field=models.CharField(default=';', max_length=5),
        ),
        migrations.AlterField(
            model_name='source',
            name='pref_ref',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
