# Generated by Django 2.2.13 on 2021-01-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publis', '0021_auto_20210115_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='type_source',
            field=models.CharField(choices=[('CORE', "Fichier d'import CORE"), ('SCIMAGO', "Fichier d'import SCIMAGO"), ('INTERNE', "Fichier d'import format interne")], default='CORE', max_length=30),
        ),
    ]
