# Generated by Django 2.2.13 on 2021-01-16 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publis', '0022_source_type_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='pref_ref',
            new_name='identifiant_source',
        ),
        migrations.RemoveField(
            model_name='source',
            name='a_charger',
        ),
    ]
