# Generated by Django 2.2.13 on 2021-01-16 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publis', '0023_auto_20210116_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referentiel',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='publis.Source'),
        ),
    ]
