# Generated by Django 2.2.18 on 2021-03-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publis', '0024_auto_20210116_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referentiel',
            name='ref_locale',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
