# Generated by Django 2.2.18 on 2021-03-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publis', '0025_auto_20210316_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('nom_hal', models.CharField(max_length=40)),
                ('id_hal', models.IntegerField()),
                ('description', models.TextField()),
                ('email_contact', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'Collection',
            },
        ),
    ]
