# Generated by Django 2.2.18 on 2021-03-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publis', '0026_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='id',
        ),
        migrations.AlterField(
            model_name='collection',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='id_hal',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='collection',
            name='nom_hal',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
