# Generated by Django 2.2.18 on 2021-03-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publis', '0027_auto_20210324_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='nom',
            field=models.CharField(default='À définir', max_length=40),
        ),
        migrations.AddField(
            model_name='publication',
            name='collections',
            field=models.ManyToManyField(blank=True, to='publis.Collection'),
        ),
    ]
