# Generated by Django 2.2.18 on 2021-03-25 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publis', '0028_auto_20210324_2301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='id_hal',
            new_name='id',
        ),
    ]
