# Generated by Django 2.2.18 on 2021-03-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publis', '0029_auto_20210325_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
