# Generated by Django 2.2.18 on 2021-03-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publis', '0030_auto_20210325_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='id_hal',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
