# Generated by Django 2.2.18 on 2021-03-25 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publis', '0032_auto_20210325_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='auteurs',
        ),
    ]
