# Generated by Django 2.2.18 on 2021-03-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publis', '0033_remove_publication_auteurs'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='auteurs',
            field=models.ManyToManyField(blank=True, to='publis.Auteur'),
        ),
    ]
