# Generated by Django 2.2.18 on 2021-03-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publis', '0034_publication_auteurs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('code', models.CharField(default='défaut', max_length=20, primary_key=True, serialize=False)),
                ('url_hal', models.CharField(default='https://api.archives-ouvertes.fr/search/', max_length=80)),
                ('annee_min_publis', models.IntegerField(default=2017)),
                ('annee_max_publis', models.IntegerField(default=2021)),
            ],
            options={
                'db_table': 'Config',
            },
        ),
        migrations.RemoveField(
            model_name='publication',
            name='equipes',
        ),
    ]
