# Generated by Django 3.1.7 on 2021-03-31 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publis', '0035_auto_20210327_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='auteurs',
        ),
    ]
