# Generated by Django 3.1.7 on 2021-03-31 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publis', '0036_remove_publication_auteurs'),
    ]

    operations = [
        migrations.AddField(
            model_name='auteur',
            name='position',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='publication',
            name='auteurs',
            field=models.ManyToManyField(blank=True, to='publis.Auteur'),
        ),
        migrations.AlterField(
            model_name='auteur',
            name='idHal',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
