# Generated by Django 3.1.7 on 2021-03-31 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publis', '0037_auto_20210331_0646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auteur',
            old_name='idHal',
            new_name='id_hal',
        ),
    ]
