# Generated by Django 3.1.7 on 2021-03-31 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publis', '0038_auto_20210331_0647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auteur',
            name='position',
        ),
        migrations.AddField(
            model_name='publication',
            name='chaine_auteurs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
