# Generated by Django 2.2.18 on 2021-03-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publis', '0039_auto_20210331_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='nom',
            field=models.CharField(default='À définir', max_length=80),
        ),
    ]
